export default function () {
    const attackCalc = {
        normal: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 0.5,
            bug: 1,
            ghost: 0,
            steel: 0.5,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 1,
            dark: 1,
            fairy: 1,
        },
        fighting: {
            normal: 2,
            fighting: 1,
            flying: 0.5,
            poison: 0.5,
            ground: 1,
            rock: 2,
            bug: 0.5,
            ghost: 0,
            steel: 2,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 0.5,
            ice: 2,
            dragon: 1,
            dark: 2,
            fairy: 0.5,
        },
        flying: {
            normal: 1,
            fighting: 2,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 0.5,
            bug: 2,
            ghost: 1,
            steel: 0.5,
            fire: 1,
            water: 1,
            grass: 2,
            electric: 0.5,
            psychic: 1,
            ice: 1,
            dragon: 1,
            dark: 1,
            fairy: 1,
        },
        poison: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 0.5,
            ground: 0.5,
            rock: 0.5,
            bug: 1,
            ghost: 0.5,
            steel: 0,
            fire: 1,
            water: 1,
            grass: 2,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 1,
            dark: 1,
            fairy: 2,
        },
        ground: {
            normal: 1,
            fighting: 1,
            flying: 0,
            poison: 2,
            ground: 1,
            rock: 2,
            bug: 0.5,
            ghost: 1,
            steel: 2,
            fire: 2,
            water: 1,
            grass: 0.5,
            electric: 2,
            psychic: 1,
            ice: 1,
            dragon: 1,
            dark: 1,
            fairy: 1,
        },
        rock: {
            normal: 1,
            fighting: 0.5,
            flying: 2,
            poison: 1,
            ground: 0.5,
            rock: 1,
            bug: 2,
            ghost: 1,
            steel: 0.5,
            fire: 2,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 1,
            ice: 2,
            dragon: 1,
            dark: 1,
            fairy: 1,
        },
        bug: {
            normal: 1,
            fighting: 0.5,
            flying: 0.5,
            poison: 0.5,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 0.5,
            steel: 0.5,
            fire: 0.5,
            water: 1,
            grass: 2,
            electric: 1,
            psychic: 2,
            ice: 1,
            dragon: 1,
            dark: 2,
            fairy: 0.5,
        },
        ghost: {
            normal: 0,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 2,
            steel: 1,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 2,
            ice: 1,
            dragon: 1,
            dark: 0.5,
            fairy: 1,
        },
        steel: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 2,
            bug: 1,
            ghost: 1,
            steel: 0.5,
            fire: 0.5,
            water: 0.5,
            grass: 1,
            electric: 0.5,
            psychic: 1,
            ice: 2,
            dragon: 1,
            dark: 1,
            fairy: 2,
        },
        fire: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 0.5,
            bug: 2,
            ghost: 1,
            steel: 2,
            fire: 0.5,
            water: 0.5,
            grass: 2,
            electric: 1,
            psychic: 1,
            ice: 2,
            dragon: 0.5,
            dark: 1,
            fairy: 1,
        },
        water: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 2,
            rock: 2,
            bug: 1,
            ghost: 1,
            steel: 1,
            fire: 2,
            water: 0.5,
            grass: 0.5,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 0.5,
            dark: 1,
            fairy: 1,
        },
        grass: {
            normal: 1,
            fighting: 1,
            flying: 0.5,
            poison: 0.5,
            ground: 2,
            rock: 2,
            bug: 0.5,
            ghost: 1,
            steel: 0.5,
            fire: 0.5,
            water: 2,
            grass: 0.5,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 0.5,
            dark: 1,
            fairy: 1,
        },
        electric: {
            normal: 1,
            fighting: 1,
            flying: 2,
            poison: 1,
            ground: 0,
            rock: 1,
            bug: 1,
            ghost: 1,
            steel: 1,
            fire: 1,
            water: 2,
            grass: 0.5,
            electric: 0.5,
            psychic: 1,
            ice: 1,
            dragon: 0.5,
            dark: 1,
            fairy: 1,
        },
        psychic: {
            normal: 1,
            fighting: 2,
            flying: 1,
            poison: 2,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 1,
            steel: 0.5,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 0.5,
            ice: 1,
            dragon: 1,
            dark: 0,
            fairy: 1,
        },
        ice: {
            normal: 1,
            fighting: 1,
            flying: 2,
            poison: 1,
            ground: 2,
            rock: 1,
            bug: 1,
            ghost: 1,
            steel: 0.5,
            fire: 0.5,
            water: 0.5,
            grass: 2,
            electric: 1,
            psychic: 1,
            ice: 0.5,
            dragon: 2,
            dark: 1,
            fairy: 1,
        },
        dragon: {
            normal: 1,
            fighting: 1,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 1,
            steel: 0.5,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 2,
            dark: 1,
            fairy: 0,
        },
        dark: {
            normal: 1,
            fighting: 0.5,
            flying: 1,
            poison: 1,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 2,
            steel: 1,
            fire: 1,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 2,
            ice: 1,
            dragon: 1,
            dark: 0.5,
            fairy: 0.5,
        },
        fairy: {
            normal: 1,
            fighting: 2,
            flying: 1,
            poison: 0.5,
            ground: 1,
            rock: 1,
            bug: 1,
            ghost: 1,
            steel: 0.5,
            fire: 0.5,
            water: 1,
            grass: 1,
            electric: 1,
            psychic: 1,
            ice: 1,
            dragon: 2,
            dark: 2,
            fairy: 1,
        },
    }
    const typeTwToEn = {
        蟲: 'bug',
        惡: 'dark',
        龍: 'dragon',
        電: 'electric',
        火: 'fire',
        妖精: 'fairy',
        格鬥: 'fighting',
        飛行: 'flying',
        幽靈: 'ghost',
        草: 'grass',
        地面: 'ground',
        冰: 'ice',
        一般: 'normal',
        毒: 'poison',
        超能力: 'psychic',
        岩石: 'rock',
        鋼: 'steel',
        水: 'water',
    }
    const typeEnToTw = {
        bug: '蟲',
        dark: '惡',
        dragon: '龍',
        electric: '電',
        fire: '火',
        fairy: '妖精',
        fighting: '格鬥',
        flying: '飛行',
        ghost: '幽靈',
        grass: '草',
        ground: '地面',
        ice: '冰',
        normal: '一般',
        poison: '毒',
        psychic: '超能力',
        rock: '岩石',
        steel: '鋼',
        water: '水',
    }
    const qualityEnToTw = {
        normal: '一般',
        rare: '稀有',
        epic: '史詩',
        legend: '傳說',
        beyond: '超越',
    }
    const typeColors = [
        {
            type: 'normal',
            color: 'rgba(220,220,220)',
            alphaColor: 'rgba(220,220,220,0.2)',
        },
        {
            type: 'fire',
            color: 'rgba(255,105,0)',
            alphaColor: 'rgba(255,105,0, 0.2)',
        },
        {
            type: 'water',
            color: 'rgba(20,185,255)',
            alphaColor: 'rgba(20,185,255, 0.2)',
        },
        {
            type: 'grass',
            color: 'rgba(180,240,0)',
            alphaColor: 'rgba(180,240,0, 0.2)',
        },
        {
            type: 'electric',
            color: 'rgba(255,255,0)',
            alphaColor: 'rgba(255,255,0, 0.2)',
        },
        {
            type: 'ice',
            color: 'rgba(20,245,255)',
            alphaColor: 'rgba(20,245,255, 0.2)',
        },
        {
            type: 'fighting',
            color: 'rgba(220,105,0)',
            alphaColor: 'rgba(220,105,0, 0.2)',
        },
        {
            type: 'poison',
            color: 'rgba(210,140,210)',
            alphaColor: 'rgba(210,140,210, 0.2)',
        },
        {
            type: 'ground',
            color: 'rgba(250,200,90)',
            alphaColor: 'rgba(250,200,90, 0.2)',
        },
        {
            type: 'flying',
            color: 'rgba(120,220,255)',
            alphaColor: 'rgba(120,220,255, 0.2)',
        },
        {
            type: 'psychic',
            color: 'rgba(240,140,220)',
            alphaColor: 'rgba(240,140,220, 0.2)',
        },
        {
            type: 'bug',
            color: 'rgba(70,200,70)',
            alphaColor: 'rgba(70,200,70, 0.2)',
        },
        {
            type: 'rock',
            color: 'rgba(180,140,100)',
            alphaColor: 'rgba(180,140,100, 0.2)',
        },
        {
            type: 'ghost',
            color: 'rgba(160,140,255)',
            alphaColor: 'rgba(160,140,255, 0.2)',
        },
        {
            type: 'dragon',
            color: 'rgba(80,120,220)',
            alphaColor: 'rgba(80,120,220, 0.2)',
        },
        {
            type: 'dark',
            color: 'rgba(120,120,120)',
            alphaColor: 'rgba(120,120,120, 0.2)',
        },
        {
            type: 'steel',
            color: 'rgba(170,200,240)',
            alphaColor: 'rgba(170,200,240, 0.2)',
        },
        {
            type: 'fairy',
            color: 'rgba(255,175,200)',
            alphaColor: 'rgba(255,175,200, 0.2)',
        },
    ]
    const getTypeColors = (type) => {
        return typeColors.find((t) => t.type === type)
    }
    return {
        attackCalc,
        typeTwToEn,
        typeEnToTw,
        qualityEnToTw,
        getTypeColors,
    }
}
